# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-19 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20150921_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.TextField()),
                ('playerNum', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournamentName', models.TextField()),
                ('teamNum', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='student',
            field=models.ManyToManyField(to='app.Student'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='classroom',
            field=models.ManyToManyField(to='app.Classroom'),
        ),
        migrations.AlterField(
            model_name='file',
            name='language',
            field=models.TextField(default=b'es'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Teacher'),
        ),
        migrations.AddField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tournament'),
        ),
        migrations.AddField(
            model_name='student',
            name='team',
            field=models.ManyToManyField(to='app.Team'),
        ),
    ]
