# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-21 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20161119_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='classroom',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
