# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-21 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20170121_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='name',
            new_name='username',
        ),
    ]
