# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-21 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20170121_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='team',
            new_name='teams',
        ),
    ]
