# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-04 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20170121_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='username',
            field=models.TextField(default=b''),
        ),
    ]
