# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-04 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20170704_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('parallelism', models.IntegerField(default=0)),
                ('logic', models.IntegerField(default=0)),
                ('flowControl', models.IntegerField(default=0)),
                ('userInteractivity', models.IntegerField(default=0)),
                ('dataRepresentation', models.IntegerField(default=0)),
                ('abstraction', models.IntegerField(default=0)),
                ('synchronization', models.IntegerField(default=0)),
                ('teams', models.ManyToManyField(to='app.Team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tournament')),
            ],
        ),
    ]
