# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-24 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='password',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
